name: tutor


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
          
      - uses: actions/checkout@v2
    
    
#       - name: Stop tutorial-usa_web_1 container
#         run: | 
#           docker stop tutorial-usa_web_1 

#       - name: Stop tutorial-usa_db_1 container
#         run: | 
#           docker stop tutorial-usa_db_1
          
#       - name: Delete tutorial-usa_web_1 container
#         run: |
#           docker rm tutorial-usa_web_1 

          
#       - name: Delete tutorial-usa_db_1 container
#         run: |
#           docker rm tutorial-usa_db_1
      - name: Restart docker service
        run : |
          sudo service docker restart
          
      - name: Run Docker-Compose
        run: |
          docker-compose up -d
            
      - name: Makemigrations
        run: |
          docker-compose run web python3 manage.py makemigrations
          
      - name: Migrate
        run: |
          docker-compose run web python3 manage.py migrate
          
      - name: Collectstatic
        run: |
          docker-compose run web python3 manage.py collectstatic 
